version: '3.6'
services:
  postgres:
    image: postgres:11.9
    container_name: telegrafo-postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=telegrafo
      - POSTGRES_PASSWORD=telegrafo
      - POSTGRES_DB=telegrafo_development
    ports:
      - '5432:5432'
